apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: latest
    kubeaid.io/managed-by: kubeaid
    kubeaid.io/sync-order: "10"
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  project: kubeaid
  sources:
    - repoURL: https://github.com/anantha1999/KubeAid
      path: argocd-helm-charts/sealed-secrets
      targetRevision: latest
      helm:
        valueFiles:
          - $values/k8s/kubeaid-demo/argocd-apps/values-sealed-secrets.yaml
    - repoURL: https://github.com/anantha1999/kubeaid-config
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
