issuer:
  enabled: true
  issuerEmail: klavs@obmondo.com
  production: true
  secret: kbm-letsencrypt-key
  solvers:
    - type: dns
      cloudProvider: cloudflare
      cloudProviderSecretRef:
        name: cloudflare-api-token-secret
        key: api-token
      dnsNames:
        - obmondo.com
        - "*.kbm.obmondo.com"
    - type: http
      http01:
        ingress:
          ingressClassName: traefik-cert-manager

cert-manager:
  cainjector:
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 1m
        memory: 128Mi
