apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ntrip-router
  namespace: traefik
spec:
  entryPoints:
    - ntrip
  routes:
    - match: HostSNI(`*`)
      services:
        - name: ntripcaster-ntripcaster
          port: 12101
  tls:
    passthrough: true
