apiVersion: v1
kind: Service
metadata:
  name: {{ include "ntripcaster.fullname" . }}-caster
  labels:
    {{- include "ntripcaster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ntripcaster.service.type }}
  ports:
    - port: 80
      targetPort: ntripcaster-http
      protocol: TCP
      name: http
    - port: {{ .Values.ntripcaster.service.port }}
      targetPort: ntripcaster
      protocol: TCP
      name: ntripcaster
  selector:
    {{- include "ntripcaster.selectorLabels" . | nindent 4 }}
