apiVersion: v1
kind: Service
metadata:
  name: {{ include "ntripcaster.fullname" . }}-relay
  labels:
    {{- include "ntripcaster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ntriprelay.service.type }}
  ports:
    - port: 80
      targetPort: ntriprelay-http
      protocol: TCP
      name: http
    - port: {{ .Values.ntriprelay.service.port }}
      targetPort: ntriprelay
      protocol: TCP
      name: ntriprelay
  selector:
    {{- include "ntripcaster.selectorLabels" . | nindent 4 }}
